io:
  dataname: shanghaiTech  # york, shanghaiTech
  model_initialize_file: FClip/ckpt/HG2/checkpoint.pth


model:
  # backbone parameters
  backbone: stacked_hourglass  # stacked_hourglass, hourglass_lines
  depth: 4
  num_stacks: 2
  num_blocks: 1
  inplanes: 64

